export const elements = {
  dropArea: document.getElementById('dropArea'),
  fileInput: document.getElementById('fileInput'),
  previewImage: document.getElementById('previewImage'),
  adjustmentsSidebar: document.getElementById('adjustmentsSidebar'),
  filterItems: document.querySelectorAll('.filter-item'),
  closeAdjustment: document.getElementById('closeAdjustment'),
  cancelAdjustment: document.getElementById('cancelAdjustment'),
  applyAdjustment: document.getElementById('applyAdjustment'),
  adjustmentTitle: document.getElementById('adjustmentTitle'),
  intensitySlider: document.getElementById('intensitySlider'),
  intensityValue: document.getElementById('intensityValue'),
  contrastSlider: document.getElementById('contrastSlider'),
  contrastValue: document.getElementById('contrastValue'),
  brightnessSlider: document.getElementById('brightnessSlider'),
  brightnessValue: document.getElementById('brightnessValue'),
  customSliders: document.getElementById('customSliders'),
  downloadBtn: document.getElementById('downloadBtn'),
  undoBtn: document.getElementById('undoBtn'),
  resetBtn: document.getElementById('resetBtn'),
  newProjectBtn: document.getElementById('newProjectBtn'),
  toast: document.getElementById('toast'),
  toastMessage: document.getElementById('toastMessage')
};
